# -*- coding: utf-8 -*-
"""Lap6_52100674

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17OCIYhW5XXfkPMrtDKVo8d-X7QuUuqfU
"""

#viducuaco
import numpy as np
w=np.array([-1,-2,1,4])

#l1 -norm
#option 1
print(np.linalg.norm(w,1))
#option2
print(sum(abs(w)))

#l2-norm
#option1
print(np.linalg.norm(w,2))
#option2
print(np.sqrt(sum(w**2)))

#loo-norm
#option1
print(np.linalg.norm(w,np.inf))
#option2
print(max(abs(w)))

#vidu cua co
import numpy as np
q='Ven cute pho mai que'
s1='Siu cute'
s2='cute'
#Ven,cute,pho,mai,que,siu
f1=[1,1,1,1,1,0]
f2=[0,1,0,0,0,1]
f3=[0,1,0,0,0,0]

D=np.vstack((f2,f3))
d=[]
for i in range(D.shape[0]):
  cs = sum(f1*D[i,:])/(np.linalg.norm(f1*2)*np.linalg.norm(D[i,:],2))
  d.append(cs)
print(d)

#maxtrix - norm
import numpy as np
A = np.array([[-1,1,0],[-2,1,3],[1,-1,0]])

#l1 -norm
#option1
print(np.linalg.norm(A,1))
#option2
print(max(sum(abs(A))))

#l2- norm
#option1
print(np.linalg.norm(A,'fro'))
#option2
print(np.sqrt(np.sum(A**2)))

#loo_norm
#option1
print(np.linalg.norm(A,np.inf))
#option2
print(max(sum(abs(A.T))))
print(max(np.sum(abs(A),axis =1)))

#bai1A1
import numpy as np
print("a)")
A1 = np.array([[1,-7],[-2,-3]])
print(max(sum(abs(A1))))
print(np.sqrt(np.sum(A1**2)))
print(max(np.sum(abs(A1),axis =1)))

#bai1A2
import numpy as np
A2 = np.array([[-2,8],[3,1]])
print("b)")
print(max(sum(abs(A2))))
print(np.sqrt(np.sum(A2**2)))
print(max(np.sum(abs(A2),axis =1)))

#bai1A3
import numpy as np
A3 = np.array([[2,-8],[3,1]])
print("c)")
print(max(sum(abs(A3))))
print(np.sqrt(np.sum(A3**2)))
print(max(np.sum(abs(A3),axis =1)))

#bai1A4
import numpy as np
A4 = np.array([[2,3],[1,-1]])
print("d)")
print(max(sum(abs(A4))))
print(np.sqrt(np.sum(A4**2)))
print(max(np.sum(abs(A4),axis =1)))

#bai1A5
import numpy as np
A5 = np.array([[5,-4,2],[-1,2,3],[-2,1,0]])
print("e)")
print(max(sum(abs(A5))))
print(np.sqrt(np.sum(A5**2)))
print(max(np.sum(abs(A5),axis =1)))

#bai2
B1=np.array([[1,-7],[2,3]])
print(np.linalg.norm(B1,np.inf))
B2=np.array([[5,-4,2],[1,2,3],[-2,1,0]])
print(np.linalg.norm(B2,np.inf))
B3=np.array([[3,6],[1,0]])
print(np.linalg.norm(B3,np.inf))
B4=np.array([[3,6,-1],[3,1,0],[2,4,-7]])
print(np.linalg.norm(B4,np.inf))
B5=np.array([[-3,0,0],[0,4,0],[0,0,2]])
print(np.linalg.norm(B5,np.inf))

#bai3
C1=np.array([[5,-4,2],[-1,2,3],[-2,1,0]])
print(np.linalg.norm(C1,'fro'))
C2=np.array([[1,7,3],[4,-2,-2],[-2,-1,1]])
print(np.linalg.norm(C2,'fro'))
C3=np.array([[2,3],[1,-1]])
print(np.linalg.norm(C3,'fro'))

#Bai4
import numpy as np
u = np.array([1,1])
v = np.array([0,1])
## cos(theta) =(u.v)/(||u||_2||v||_2)
cs = sum(u*v)/(np.linalg.norm(u,2)*np.linalg.norm(v,2))
print(cs)

#bai5
import numpy as np
#a)
u = np.array([2,3])
# unit_vector = u/||u||_2
unit = u/np.linalg.norm(u,2)
print(unit)
#b)
u = np.array([1,2,3])
# unit_vector = u/||u||_2
unit = u/np.linalg.norm(u,2)
print(unit)

#bai6
import numpy as np
print("Bai6")
def bai6(u,v):
  ## cos(theta) = (u.v)/(||u||_2||v||-2)
  cs = sum(u*v)/(np.linalg.norm(u,2)*np.linalg.norm(v,2))
  print(cs)
print("a)")
v1 = np.array([1,2,3])
s2 = np.array([7,4,3])
bai6(v1,s2)
print("b)")
s3 = np.array([2,1,9])
s2 = np.array([7,4,3])
bai6(s3,s2)
print("a)")
v1 = np.array([1,2,3])
s3 = np.array([2,1,9])
bai6(v1,s3)

#bai7
import numpy as np
def decode(a):
  u=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',' ']
  for i in range(0,27):
    if(a==i+1):
      return u[i]
A=[[1,2,3],[2,1,2],[3,2,4]]
E=[[80,98,99,85,106,94],[71,92,76,95,100,92],[124,163,140,160,176,161]]
D=np.linalg.inv(A)@E
D=D-3
D=D.T
chr=""
for i in range(0,D.shape[0]):
    for j in range(0,D.shape[1]):
        chr+=decode(round(D[i][j]))
print(chr)

#bai8
import numpy as np
def cau8a():
    message = "ATTACK"
    A = np.array([[3, 4, 5],
                  [1, 3, 1],
                  [1, 1, 2]])
    E = [[],[],[]]
    k = 0
    for i in range(int(len(message)/3)):
        for j in range(3):
            if message[k] == ' ':
                E[j].append(27)
            else:
                E[j].append(ord(message[k])-64)
        k += 1
    
    E = np.array(E)
    print(np.matmul(A, E))

def cau8b():
    message = "LINEAR ALGEBRA LABORATORY"
    A = np.array([[3, 4, 5],
                  [1, 3, 1],
                  [1, 1, 2]])
    E = [[],[],[]]
    k = 0
    for i in range(int(len(message)/3)):
        for j in range(3):
            if message[k] == ' ':
                E[j].append(27)
            else:
                E[j].append(ord(message[k])-64)
        k += 1
    
    E = np.array(E)
    print(np.matmul(A, E))
print("8a")
cau8a()
print("8b")
cau8b()

#bai9
Doc1=[0,4,0,0,0,2,1,3]
Doc2=[3,1,4,3,1,2,0,1]
Doc3=[3,0,0,0,3,0,3,0]
Doc4=[0,1,0,3,0,0,2,0]
Doc5=[2,2,2,3,1,4,0,2]
D=np.vstack((Doc2,Doc3,Doc4,Doc5))
d=[]
for i in range(D.shape[0]):
  cs=sum(Doc1*D[i,:])/(np.linalg.norm(Doc1,2)*np.linalg.norm(D[i,:],2))
  d.append(cs)
print(d)

#bai10
q=[0,0,0.7,0.5,0,0.3]
D1=[1,0.5,0.3,0,0,0]
D2=[0,1,0.8,0.7,0,0]
D3=[0,1,0.8,0.7,0,0]
D4=[0,0.9,1,0.5,0,0]
D5=[0,0,0,1,0,1]
D6=[0,0,0,0,0.7,0]
D7=[0.5,0,0.7,0,0,0.9]
D8=[0,0.6,0,1,0.3,0.2]
D=np.vstack((D1,D2,D3,D4,D5,D6,D7,D8))
d=[]
for i in range(D.shape[0]):
  cs=sum(q*D[i,:])/(np.linalg.norm(q,2)*np.linalg.norm(D[i,:],2))
  d.append(cs)
print(d)

